server:
  port: 9090

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/how2java?characterEncoding=UTF-8"
    username: "root"
    password: "02881902"
    driver-class-name: "com.mysql.jdbc.Driver"
